name: "finetune_decoder_mergeragain"
encode_decoder_mode: "seperate_train"
output_path: "/data2/saikiran.tedla/hdrvideo/diff/models/train/finetune_decoder_mergeragain"
dataset_base_path: "/data2/saikiran.tedla/hdrvideo/diff/data/stuttgart" # Base path of the dataset
dataset_metadata_path: null
max_pixels: 921600
height: 704
width: 1280
crop_size_w: 256
crop_size_h: 256
num_frames: 15
data_file_keys: "image,video"
dataset_repeat: 1
model_paths: null # auto-resumes from latest checkpoint in output_path
model_id_with_origin_paths: "Wan-AI/Wan2.2-TI2V-5B:models_t5_umt5-xxl-enc-bf16.pth,Wan-AI/Wan2.2-TI2V-5B:diffusion_pytorch_model*.safetensors,Wan-AI/Wan2.2-TI2V-5B:Wan2.2_VAE.pth"
learning_rate: 0.00001
num_epochs: 200
remove_prefix_in_ckpt: "pipe."
trainable_models: "vae.model.decoder,merge_decoder"
lora_base_model: null
lora_target_modules: "q,k,v,o,ffn.0,ffn.2"
lora_rank: 32
lora_checkpoint: null
extra_inputs: "bracket_video"
use_gradient_checkpointing_offload: false
gradient_accumulation_steps: 16
max_timestep_boundary: 1.0
min_timestep_boundary: 0.0
find_unused_parameters: false
save_steps: null
dataset_num_workers: 4
weight_decay: 0.01
loss_type: "hdr_l1"
use_vae_ea: true
ea_num_heads: 4
