name: "three_exposures_justcrf"
encode_decoder_mode: "seperate_debevec"
input_type: "crf"
output_path: "./models/train/three_exposures_justcrf"
dataset_base_path: "/data2/saikiran.tedla/hdrvideo/diff/data/stuttgart" # Base path of the dataset
dataset_metadata_path: null
max_pixels: 921600
height: 512
width: 768
num_frames: 3
data_file_keys: "image,video"
dataset_repeat: 1
model_paths: null #[\"/data2/saikiran.tedla/hdrvideo/diff/models/train/finetune_decoder_justmerger/checkpoints/epoch-199.safetensors\"] # Paths to load models. In JSON format.
model_id_with_origin_paths: "Wan-AI/Wan2.2-TI2V-5B:models_t5_umt5-xxl-enc-bf16.pth,Wan-AI/Wan2.2-TI2V-5B:diffusion_pytorch_model*.safetensors,Wan-AI/Wan2.2-TI2V-5B:Wan2.2_VAE.pth"
decoder_path: "/data2/saikiran.tedla/hdrvideo/diff/models/train/finetune_decoder_justmerger/checkpoints/epoch-199.safetensors"
learning_rate: 0.00003
num_epochs: 201
remove_prefix_in_ckpt: "pipe."
trainable_models: "dit"
lora_base_model: null #"dit"
lora_target_modules: "q,k,v,o,ffn.0,ffn.2"
lora_rank: 32
lora_checkpoint: null
extra_inputs: "condition_video"
use_gradient_checkpointing_offload: false
use_gradient_checkpointing: true
gradient_accumulation_steps: 16
max_timestep_boundary: 1.0
min_timestep_boundary: 0.0
find_unused_parameters: false
save_steps: null
dataset_num_workers: 15
weight_decay: 0.01
